language: generic

before_install:
  - sudo apt-get update
  - sudo apt-get install -y apm=1.0.0

script:
  - apm --version
  - apm install
  - apm build
  - apm test

after_success:
  - for file in $(find . -type f -name "*.hg"); do
      hg activate $file;
    done
    
