 # ملف تكوين لغة HG

# إعدادات اللغة
language:
  name: HG
  version: 1.0
  author: APMSHAP 
  description: A powerful and advanced programming language for building sophisticated applications.

# إعدادات التنسيق
formatting:
  font_family: 'Roboto, sans-serif'
  font_size: 16px
  font_color: '#333333'
  background_color: '#F0F0F0'
  border_color: '#CCCCCC'
  border_radius: 5px
  box_shadow: '0 0 10px rgba(0, 0, 0, 0.1)'
  text_align: left

# إعدادات البيئة
environment:
  development:
    name: Development Environment
    description: Setting up the development environment for Advanced HG Language.
    tools:
      - name: Node.js
        version: 14.x
        description: JavaScript runtime for building server-side and networking applications.
      - name: Cloud Storage
        description: Cloud-based storage for hosting applications and data.
      - name: Text Editor
        description: A text editor for writing HG code, such as Visual Studio Code or Sublime Text.

# مكتبة الوظائف
libraries:
  - name: math
    functions:
      - name: add
        description: Add two numbers together.
      - name: subtract
        description: Subtract one number from another.

# إعدادات التشغيل
execution:
  entry_point: main.hg
  command: python run.py

# إعدادات الترجمة
translation:
  enabled: true
  languages:
    - name: Arabic
      code: ar
    - name: Spanish
      code: es

# إعدادات الأمان
security:
  firewall:
    enabled: true
    rules:
      - name: AllowHTTP
        port: 80
        protocol: TCP
        action: ALLOW
      - name: AllowHTTPS
        port: 443
        protocol: TCP
        action: ALLOW
        
